### ISSUE TITLE
this project can work?

### ISSUE THREAD

**Issue by IDhammaI** [im-razvan/CS2_SoundESP#1]
......

**Comment by IDhammaI** [comment]
Traceback (most recent call last):
  File "C:\Users\IDhammaI\Desktop\python-learn\test\main.py", line 84, in <module>
    main()
  File "C:\Users\IDhammaI\Desktop\python-learn\test\main.py", line 69, in main
    if localPlayer.team != player.team and player.health > 0:
  File "C:\Users\IDhammaI\Desktop\python-learn\test\main.py", line 29, in team
    return pm.r_int(self.proc, self.pawn + Offsets.m_iTeamNum)
nimpy.AccessViolationDefect: Unexpected error encountered: Read failed [Address: 0x0000000042D9CBBF]
